name: test-and-lint

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install
      run: make install

    - name: Test
      run: make test

    - name: Lint
      run: make lint
